name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] - "
labels:
  - enhancement
assignees: []

body:
  - type: dropdown
    id: affected_package
    attributes:
      label: "Affected Package"
      description: "Select the package or module this feature request relates to."
      options:
        - "appsync-realtime-client"
        - "appsync-utils"
        - "appsync-graphql-construct"
        - "graphql-transformer"
    validations:
      required: false
  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Please provide a detailed description of the feature or improvement."
      placeholder: "Describe the feature here..."
    validations:
      required: true
