import fs from "node:fs";
import path from "node:path";
import prettier from "@prettier/sync";
import { buildSync } from "esbuild";

export function getOrCreateDir(loc: string) {
  const dirPath = path.resolve(loc);

  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  return dirPath;
}

export function cleanDir(loc: string) {
  const dirPath = path.resolve(loc);

  if (fs.existsSync(dirPath)) {
    fs.rmSync(dirPath, { recursive: true });

    fs.mkdirSync(dirPath);
  }

  return dirPath;
}

export function ensureOutputDirectory(loc: string, clean = false) {
  const dirPath = getOrCreateDir(loc);

  if (clean && fs.readdirSync(dirPath).length) {
    return cleanDir(dirPath);
  }

  return dirPath;
}

export function printFile(path: string, content: string) {
  return fs.writeFileSync(path, content, { encoding: "utf-8" });
}

const fileHeader = `/* !!! This is code generated by GraphQLGenerator. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck`;

export function prettyPrintFile(path: string, content: string) {
  const contentWithHeader = `${fileHeader}\n\n${content}`;
  return printFile(path, prettier.format(contentWithHeader, { parser: "typescript" }));
}

export function buildPaths(paths: string[], outDir: string) {
  return buildSync({
    entryPoints: paths,
    outdir: outDir,
    target: "esnext",
    sourcemap: "inline",
    sourcesContent: false,
    treeShaking: true,
    platform: "node",
    format: "esm",
    minify: false,
    bundle: true,
    write: false,
    external: ["@aws-appsync/utils"],
  });
}

export function dirname(metaUrl: string) {
  return path.dirname(new URL(metaUrl).pathname);
}
